// This is an autogenerated file from Firebase Studio.

import {generateVisualPrompts} from '@/ai/flows/generate-visual-prompts';
import {appRoute} from '@genkit-ai/next';

export const POST = appRoute(generateVisualPrompts);
