// This is an autogenerated file from Firebase Studio.

import { generateVisualPrompts } from '@/ai/flows/generate-visual-prompts';
import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest) {
    try {
        const body = await req.json();
        const result = await generateVisualPrompts(body);
        return NextResponse.json(result);
    } catch (error: any) {
        return NextResponse.json({ error: error.message || 'An error occurred' }, { status: 500 });
    }
}
